// cosky-dashboard/src/pages/Login.tsx
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Form, Input, Button, Card, message } from 'antd'
import { UserOutlined, LockOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router'
import { useAuth } from '../contexts/AuthContext'
import { authenticateApi } from '../api'

interface LoginFormValues {
  username: string
  password: string
}

export default function Login() {
  const navigate = useNavigate()
  const { login } = useAuth()

  const onFinish = async (values: LoginFormValues) => {
    try {
      const tokenResponse = await authenticateApi.login(values.username, {
        body: { password: values.password }
      })
      login(tokenResponse)
      message.success('Login successful')
      navigate('/home')
    } catch (error) {
      console.error('Login failed:', error)
      message.error('Login failed')
    }
  }

  return (
    <div
      style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: '100vh',
        background: '#f0f2f5',
      }}
    >
      <Card title="CoSky Dashboard Login" style={{ width: 400 }}>
        <Form name="login" onFinish={onFinish} autoComplete="off">
          <Form.Item
            name="username"
            rules={[{ required: true, message: 'Please input your username!' }]}
          >
            <Input prefix={<UserOutlined />} placeholder="Username" />
          </Form.Item>

          <Form.Item
            name="password"
            rules={[{ required: true, message: 'Please input your password!' }]}
          >
            <Input.Password prefix={<LockOutlined />} placeholder="Password" />
          </Form.Item>

          <Form.Item>
            <Button type="primary" htmlType="submit" block>
              Log in
            </Button>
          </Form.Item>
        </Form>
      </Card>
    </div>
  )
}

// cosky-dashboard/src/app/components/login/login.component.ts
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, OnInit} from '@angular/core';
import {HOME_PATH, SecurityService} from "../../security/SecurityService";
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import {Router} from "@angular/router";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup;
  username!: string;
  password!: string;

  constructor(private securityService: SecurityService
    , private router: Router
    , private formBuilder: FormBuilder) {
  }

  ngOnInit(): void {
    if (this.securityService.authenticated()) {
      this.router.navigate([HOME_PATH])
    }
    const controlsConfig = {
      username: [this.username, [Validators.required]],
      password: [this.password, [Validators.required]]
    };
    this.loginForm = this.formBuilder.group(controlsConfig);
  }


  signIn() {
    this.securityService.signIn(this.username, this.password);
  }
}

<!--
  ~ Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<nz-layout style="height: 100vh;">
  <nz-header>
    <nz-row>
      <nz-col nzSpan="6">
        <a href="https://github.com/Ahoo-Wang/CoSky" target="_blank">
        <h1 style="color: white">CoSky</h1>
      </a>
      </nz-col>
      <nz-col nzOffset="6" nzSpan="12">
        <ul nz-menu nzTheme="dark" nzMode="horizontal" style="float: right">
          <li nz-menu-item>
            <a href="https://github.com/Ahoo-Wang/CoSky" target="_blank">Home</a>
          </li>
          <li nz-menu-item>
            <a href="https://github.com/Ahoo-Wang/CoSky" target="_blank">Documentation</a>
          </li>
          <li nz-menu-item>
            <i nz-icon nzType="github"></i>
            <a href="https://github.com/Ahoo-Wang/CoSky" target="_blank">GitHub</a>
          </li>
        </ul>
      </nz-col>
    </nz-row>
  </nz-header>
  <nz-content>
    <nz-card class="login-card" [nzBordered]="false" nzTitle="Sign in to CoSky">
      <form nz-form [formGroup]="loginForm" (ngSubmit)="signIn()">
        <nz-form-item>
          <nz-form-control nzErrorTip="Please input your username!">
            <nz-input-group nzPrefixIcon="user" nzSize="large">
              <input type="text" nz-input formControlName="username" [(ngModel)]="username" placeholder="Username"/>
            </nz-input-group>
          </nz-form-control>
        </nz-form-item>
        <nz-form-item>
          <nz-form-control nzErrorTip="Please input your Password!">
            <nz-input-group nzPrefixIcon="lock" nzSize="large">
              <input type="password" nz-input formControlName="password" [(ngModel)]="password" placeholder="Password"/>
            </nz-input-group>
          </nz-form-control>
        </nz-form-item>
        <button nz-button nzType="primary" [disabled]="!loginForm.valid" nzSize="large" nzBlock>Sign In</button>
      </form>
    </nz-card>
  </nz-content>
  <nz-footer style="text-align: center;">
    <a href="https://github.com/Ahoo-Wang/CoSky" target="_blank"
       title="High-performance, low-cost microservice governance platform. Service Discovery and Configuration Service.">CoSky</a>
    © 2021-present
  </nz-footer>
</nz-layout>
