// dashboard/src/pages/config/ConfigImporter.tsx
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, {useEffect} from 'react';
import {useExecutePromise} from "@ahoo-wang/fetcher-react";
import {App, Button, Form, Space} from "antd";
import {configApiClient} from "../../services/clients.ts";
import Dragger from "antd/es/upload/Dragger";
import {InboxOutlined} from "@ant-design/icons";
import {ImportPolicySelector} from "./ImportPolicySelector.tsx";
import {UploadChangeParam} from "antd/es/upload/interface";
import {ImportResponse} from "../../generated";

interface ConfigImporterProps {
    namespace: string;
    onSuccess: () => void;
    onCancel: () => void;
}

export const ConfigImporter: React.FC<ConfigImporterProps> = ({namespace, onSuccess, onCancel}) => {
    const {message} = App.useApp()
    const [form] = Form.useForm();
    const {loading, execute} = useExecutePromise<ImportResponse>({
        onSuccess: (result) => {
            message.success(`ToTal : ${result.total} , Succeeded : ${result.succeeded} . `)
            onSuccess();
        },
        onError: () => {
            message.error('Import config failed')
        },
    })
    const handleFinish = (values: { policy: string; importZip: UploadChangeParam<File> }) => {
        const formData = new FormData();
        formData.append('policy', values.policy);
        formData.append('importZip', values.importZip.file);
        execute(() => {
            return configApiClient.importZip(namespace, {
                body: formData
            })
        })
    };
    useEffect(() => {
        form.setFieldValue('policy', 'skip')
    }, [form]);
    return (
        <Form form={form} onFinish={handleFinish}>
            <Form.Item name="policy" label='Import Policy'>
                <ImportPolicySelector/>
            </Form.Item>
            <Form.Item name="importZip"
                       rules={[
                           {
                               required: true,
                               message: 'Please select a file!'
                           }
                       ]}>
                <Dragger multiple={false} maxCount={1} accept=".zip" beforeUpload={() => false}>
                    <p className="ant-upload-drag-icon">
                        <InboxOutlined/>
                    </p>
                    <p className="ant-upload-text">Click or drag ZIP-file to this area to upload</p>
                </Dragger>
            </Form.Item>
            <Form.Item>
                <Space>
                    <Button type="primary" htmlType="submit" loading={loading}>
                        Submit
                    </Button>
                    <Button onClick={onCancel}>
                        Cancel
                    </Button>
                </Space>
            </Form.Item>
        </Form>
    );
};

// cosky-dashboard/src/app/components/config/config-importer/config-importer.component.ts
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, EventEmitter, OnInit, Output} from '@angular/core';
import {ConfigClient, ImportPolicy} from '../../../api/config/ConfigClient';
import {NzUploadChangeParam, NzUploadFile} from 'ng-zorro-antd/upload';
import {NamespaceContext} from '../../../core/NamespaceContext';
import {NzMessageService} from 'ng-zorro-antd/message';


@Component({
  selector: 'app-config-importer',
  templateUrl: './config-importer.component.html',
  styleUrls: ['./config-importer.component.scss']
})
export class ConfigImporterComponent implements OnInit {
  @Output() afterImport: EventEmitter<boolean> = new EventEmitter<boolean>();
  importPolicy: ImportPolicy = 'skip';

  constructor(private namespaceContext: NamespaceContext,
              private configClient: ConfigClient,
              private messageService: NzMessageService) {
  }

  ngOnInit(): void {
  }

  getImportData = (file: NzUploadFile) => {
    return {
      policy: this.importPolicy
    };
  };

  getImportUrl(): string {
    return this.configClient.getImportUrl(this.namespaceContext.ensureCurrentNamespace());
  }

  handleChange({file, fileList}: NzUploadChangeParam): void {
    const status = file.status;
    if (status !== 'uploading') {
      console.log(file, fileList);
    }
    if (status === 'done') {
      this.afterImport.emit(true);
      this.messageService.success(`${file.name} file uploaded successfully.`);
    } else if (status === 'error') {
      this.afterImport.emit(false);
      this.messageService.error(`${file.name} file upload failed.`);
    }
  }

}

<!--
  ~ Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div nz-row>
  <div nz-col [nzSpan]="4" style="font-size: 14px;height: 32px;line-height: 32px;">
    <label>Import Policy :</label>
  </div>
  <div nz-col [nzSpan]="16">
    <nz-select [(ngModel)]="importPolicy">
      <nz-option nzValue="skip" nzLabel="skip"></nz-option>
      <nz-option nzValue="overwrite" nzLabel="overwrite"></nz-option>
    </nz-select>
  </div>
</div>

<nz-card>
  <nz-upload
    nzAccept="application/zip"
    nzType="drag"
    nzFileType="application/zip"
    [nzData]="getImportData"
    nzName="importZip"
    [nzAction]="getImportUrl()"
    (nzChange)="handleChange($event)"
  >
    <p class="ant-upload-drag-icon">
      <i nz-icon nzType="inbox"></i>
    </p>
    <p class="ant-upload-text">Click or drag ZIP-file to this area to upload</p>
  </nz-upload>
</nz-card>
