// cosky-dashboard/src/app/components/namespace/namespace.component.ts
import {Component, OnInit} from '@angular/core';
import {NamespaceClient} from '../../api/namespace/NamespaceClient';
import {NamespaceContext} from '../../core/NamespaceContext';
import {NzMessageService} from 'ng-zorro-antd/message';


@Component({
  selector: 'app-namespace',
  templateUrl: './namespace.component.html',
  styleUrls: ['./namespace.component.scss']
})
export class NamespaceComponent implements OnInit {
  namespaces: string[] = [];

  constructor(private namespaceContext: NamespaceContext,
              private namespaceClient: NamespaceClient,
              private messageService: NzMessageService) {
  }

  getNamespaces(): void {
    this.namespaceClient.getNamespaces().subscribe(namespaces => {
      this.namespaces = namespaces;
    });
  }


  ngOnInit(): void {
    this.getNamespaces();
  }

  removeNamespace(namespace: string): void {
    this.namespaceClient.removeNamespace(namespace).subscribe(result => {
      this.messageService.success(`Namespace:[${namespace}] removal successful.`);
      this.getNamespaces();
    });
  }

  addNamespace(namespace: string): void {
    this.namespaceClient.setNamespace(namespace).subscribe(() => {
      this.messageService.success(`Namespace:[${namespace}] added successful.`);
      this.getNamespaces();
    });
  }

  isSystem(namespace: string): boolean {
    return this.namespaceContext.isSystem(namespace);
  }
}

<!--
  ~ /*
  ~  * Copyright [2021-2021] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
  ~  *
  ~  * Licensed under the Apache License, Version 2.0 (the "License");
  ~  * you may not use this file except in compliance with the License.
  ~  * You may obtain a copy of the License at
  ~  *
  ~  *      http://www.apache.org/licenses/LICENSE-2.0
  ~  *
  ~  * Unless required by applicable law or agreed to in writing, software
  ~  * distributed under the License is distributed on an "AS IS" BASIS,
  ~  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~  * See the License for the specific language governing permissions and
  ~  * limitations under the License.
  ~  */
  -->

<div nz-row class="content-header">
  <div nz-col nzOffset="16" [nzSpan]="8">
    <nz-input-group nzSearch nzSize="large" [nzAddOnAfter]="suffixButton">
      <input type="text" nz-input placeholder="Namespace" #addNamespaceEle/>
    </nz-input-group>
    <ng-template #suffixButton>
      <button nz-button nzType="primary" nzSize="large" (click)="addNamespace(addNamespaceEle.value)">Add namespace
      </button>
    </ng-template>
  </div>
</div>

<nz-table class="content-body" #basicTable [nzFrontPagination]="false" [nzBordered]="true" [nzData]="namespaces" nzShowSizeChanger
          [nzPageSizeOptions]="[10,20,30,50,100]">
  <thead>
  <tr>
    <th>Namespace</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <tr *ngFor="let namespace of basicTable.data">
    <td>{{namespace}}</td>
    <td>
      <button
        nz-popconfirm
        [nzPopconfirmTitle]="'Are you sure delete this namespace?'"
        nzPopconfirmPlacement="top"
        [disabled]="isSystem(namespace)"
        nzType="dashed"
        nz-button
        (nzOnConfirm)="removeNamespace(namespace)"
        nzDanger
      >
        <i nz-icon nzType="delete" nzTheme="outline"></i>
      </button>
    </td>
  </tr>
  </tbody>
</nz-table>

// cosky-dashboard/src/pages/Namespace.tsx
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Typography, Table, Button, Space } from 'antd'
import { PlusOutlined, ReloadOutlined } from '@ant-design/icons'

const { Title } = Typography

interface NamespaceData {
  key: string
  namespace: string
  description: string
}

const columns = [
  {
    title: 'Namespace',
    dataIndex: 'namespace',
    key: 'namespace',
  },
  {
    title: 'Description',
    dataIndex: 'description',
    key: 'description',
  },
  {
    title: 'Action',
    key: 'action',
    render: () => (
      <Space size="middle">
        <Button type="link">Edit</Button>
        <Button type="link" danger>Delete</Button>
      </Space>
    ),
  },
]

const data: NamespaceData[] = []

export default function Namespace() {
  return (
    <div>
      <div className="content-header">
        <Title level={2}>Namespace Management</Title>
        <Space>
          <Button type="primary" icon={<PlusOutlined />}>
            Add Namespace
          </Button>
          <Button icon={<ReloadOutlined />}>
            Refresh
          </Button>
        </Space>
      </div>
      <div className="content-body">
        <Table columns={columns} dataSource={data} />
      </div>
    </div>
  )
}
