// cosky-dashboard/src/app/components/service/service.component.ts
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, OnInit} from '@angular/core';
import {ServiceStatDto} from '../../api/service/ServiceStatDto';
import {ServiceClient} from '../../api/service/ServiceClient';
import {NamespaceContext} from '../../core/NamespaceContext';
import {ServiceInstanceDto} from '../../api/service/ServiceInstanceDto';
import {InstanceEditorService} from './instance-editor.service';
import {NzMessageService} from 'ng-zorro-antd/message';
import {RowExpand} from '../../model/RowExpand';

@Component({
  selector: 'app-service',
  templateUrl: './service.component.html',
  styleUrls: ['./service.component.scss']
})
export class ServiceComponent implements OnInit {
  services: ServiceStatDto[] = [];
  displayServices!: RowExpand<ServiceStatDto>[];
  searchVisible = false;
  searchServiceId = '';
  instanceSortOrder = 'ascend';

  constructor(private namespaceContext: NamespaceContext,
              private serviceClient: ServiceClient,
              private messageService: NzMessageService,
              private instanceEditorService: InstanceEditorService) {

  }

  ngOnInit(): void {
    this.getServices();
    this.namespaceContext.subscribeNamespaceChanged('/service', namespace => {
      this.getServices();
    });
  }

  private asDisplayData(sourceData: ServiceStatDto[]): RowExpand<ServiceStatDto>[] {
    return sourceData.map(source => {
      return RowExpand.of(source);
    });
  }

  getServices(): void {
    this.serviceClient.getServiceStats(this.namespaceContext.ensureCurrentNamespace()).subscribe(services => {
      this.services = services;
      this.displayServices = this.asDisplayData(services);
    });
  }

  search(): void {
    this.searchVisible = false;
    if (this.searchServiceId.length === 0) {
      this.displayServices = this.asDisplayData(this.services);
      return;
    }
    this.displayServices = this.services.filter((item) => item.serviceId.indexOf(this.searchServiceId) !== -1)
      .map(item => RowExpand.of(item));
  }

  reset(): void {
    this.searchServiceId = '';
    this.search();
  }

  addService(serviceId: string): void {
    if (!serviceId){
      this.messageService.error(`serviceId can not be empty!`);
      return;
    }
    this.serviceClient.addService(this.namespaceContext.ensureCurrentNamespace(), serviceId)
      .subscribe(result => {
        if (result) {
          this.messageService.success(`The service[${serviceId}] was added successfully`);
        }
        this.getServices();
      });
  }

  removeService(serviceId: string): void {
    this.serviceClient.removeService(this.namespaceContext.ensureCurrentNamespace(), serviceId)
      .subscribe(result => {
        if (result) {
          this.messageService.success(`The service[${serviceId}] was deleted successfully`);
        }
        this.getServices();
      });
  }

  openEditInstance(serviceId: string, instance?: ServiceInstanceDto): void {
    this.instanceEditorService.openEditInstance(serviceId, instance, result => this.getServices());
  }

  compareInstanceCount(left: RowExpand<ServiceStatDto>, right: RowExpand<ServiceStatDto>) {
    return left.data.instanceCount - right.data.instanceCount;
  }
}

<!--
  ~ Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div nz-row class="content-header">
  <div nz-col nzOffset="16" [nzSpan]="8">
    <nz-input-group nzSearch nzSize="large" [nzAddOnAfter]="suffixButton">
      <input type="text" nz-input placeholder="Service Id" #addServiceEle/>
    </nz-input-group>
    <ng-template #suffixButton>
      <button nz-button nzType="primary" nzSize="large" (click)="addService(addServiceEle.value)">Add service</button>
    </ng-template>
  </div>
</div>

<nz-table class="content-body" #basicTable [nzBordered]="true" [nzData]="displayServices" nzShowSizeChanger
          [nzPageSizeOptions]="[10,20,30,50,100]">
  <thead>
  <tr>
    <th>Service Id
      <nz-filter-trigger [(nzVisible)]="searchVisible" [nzActive]="searchServiceId.length > 0"
                         [nzDropdownMenu]="searchMenu">
        <i nz-icon nzType="search"></i>
      </nz-filter-trigger>
    </th>
    <th [nzSortOrder]="instanceSortOrder" [nzSortFn]="compareInstanceCount">Instance Count</th>
    <th>Action</th>
    <th>Expand all instances</th>
  </tr>
  </thead>
  <tbody>
  <ng-template ngFor let-stat [ngForOf]="basicTable.data">
    <tr>
      <td>{{stat.data.serviceId}}</td>
      <td>{{stat.data.instanceCount}}</td>
      <td>
        <nz-button-group>
          <button nz-button nzType="primary" (click)="openEditInstance(stat.data.serviceId)">
            <i nz-icon nzType="appstore-add"></i>
            Add instance
          </button>
          <button
            nz-popconfirm
            nzPopconfirmTitle="Are you sure delete this service?"
            nzPopconfirmPlacement="top"
            nz-button
            (nzOnConfirm)="removeService(stat.data.serviceId)"
            nzDanger
          >
            <i nz-icon nzType="delete" nzTheme="outline"></i>
          </button>
        </nz-button-group>
      </td>
      <td [(nzExpand)]="stat.expand"></td>
    </tr>
    <ng-template [ngIf]="stat.expand">
      <tr [nzExpand]="stat.expand">
        <app-service-instance-list [serviceId]="stat.data.serviceId"></app-service-instance-list>
      </tr>
    </ng-template>
  </ng-template>
  </tbody>
</nz-table>

<nz-dropdown-menu #searchMenu="nzDropdownMenu">
  <div class="ant-table-filter-dropdown">
    <div class="search-box">
      <input type="text" nz-input placeholder="Search serviceId" [(ngModel)]="searchServiceId"
             (keyup.enter)="search()"/>
      <button nz-button nzSize="small" nzType="primary" (click)="search()" class="search-button">
        Search
      </button>
      <button nz-button nzSize="small" (click)="reset()">Reset</button>
    </div>
  </div>
</nz-dropdown-menu>

// cosky-dashboard/src/pages/Service.tsx
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Typography, Table, Button, Space } from 'antd'
import { ReloadOutlined } from '@ant-design/icons'
import { useNamespace } from '../contexts/NamespaceContext'

const { Title } = Typography

interface ServiceData {
  key: string
  serviceName: string
  instanceCount: number
  status: string
}

const columns = [
  {
    title: 'Service Name',
    dataIndex: 'serviceName',
    key: 'serviceName',
  },
  {
    title: 'Instance Count',
    dataIndex: 'instanceCount',
    key: 'instanceCount',
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
  },
  {
    title: 'Action',
    key: 'action',
    render: () => (
      <Space size="middle">
        <Button type="link">View Instances</Button>
      </Space>
    ),
  },
]

const data: ServiceData[] = []

export default function Service() {
  const { currentNamespace } = useNamespace()

  return (
    <div>
      <div className="content-header">
        <Title level={2}>Service Discovery</Title>
        <p>Namespace: {currentNamespace}</p>
        <Space>
          <Button icon={<ReloadOutlined />}>
            Refresh
          </Button>
        </Space>
      </div>
      <div className="content-body">
        <Table columns={columns} dataSource={data} />
      </div>
    </div>
  )
}
