// cosky-dashboard/src/app/components/user/user.component.ts
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, OnInit} from '@angular/core';
import {UserDto} from "../../api/user/UserDto";
import {UserClient} from "../../api/user/UserClient";
import {NzDrawerService} from "ng-zorro-antd/drawer";
import {UserEditorComponent} from "./user-editor/user-editor.component";
import {UserAddComponent} from "./user-add/user-add.component";
import {Clone} from "../../util/Clone";
import {NzMessageService} from "ng-zorro-antd/message";

@Component({
  selector: 'app-user',
  templateUrl: './user.component.html',
  styleUrls: ['./user.component.scss']
})
export class UserComponent implements OnInit {
  users: UserDto[] = [];

  constructor(private userClient: UserClient, private drawerService: NzDrawerService, private messageService: NzMessageService) {
  }

  loadUsers() {
    this.userClient.query().subscribe(resp => {
      this.users = resp;
    })
  }

  ngOnInit(): void {
    this.loadUsers();
  }

  removeUser(user: UserDto) {
    this.userClient.removeUser(user.username).subscribe(resp => {
      this.loadUsers();
    })
  }

  unlock(user: UserDto) {
    this.userClient.unlock(user.username).subscribe(resp => {
      this.messageService.success(`user:${user.username} unlock success!`)
    })
  }

  isSystem(user: UserDto) {
    return 'cosky' === user.username;
  }

  openAdd() {

    const drawerRef = this.drawerService.create<UserAddComponent, {}, string>({
      nzTitle: "Add User",
      nzWidth: '40%',
      nzContent: UserAddComponent
    });
    drawerRef.afterOpen.subscribe(() => {
      drawerRef.getContentComponent()?.afterAdd.subscribe(result => {
        if (result) {
          drawerRef.close('Operation successful');
        }
        this.loadUsers();
      });
    });
  }

  openEditor(user: UserDto) {
    const drawerRef = this.drawerService.create<UserEditorComponent, {}, string>({
      nzTitle: `Edit User [${user.username}] Role`,
      nzWidth: '30%',
      nzContent: UserEditorComponent,
      nzContentParams: {
        user: Clone.deep(user)
      }
    });
    drawerRef.afterOpen.subscribe(() => {
      drawerRef.getContentComponent()?.afterSave.subscribe(result => {
        if (result) {
          drawerRef.close('Operation successful');
        }
        this.loadUsers();
      });
    });
  }
}

<!--
  ~ Copyright [2021-2021] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div nz-row class="content-header">
  <div nz-col nzOffset="20" [nzSpan]="4">
    <button nz-button nzType="primary" nzSize="large" (click)="openAdd()">
      <i nz-icon nzType="user-add" nzTheme="outline"></i>Add User
    </button>
  </div>
</div>

<nz-table class="content-body" #basicTable [nzFrontPagination]="false" [nzBordered]="true" [nzData]="users"
          nzShowSizeChanger
          [nzPageSizeOptions]="[10,20,30,50,100]">
  <thead>
  <tr>
    <th>Username</th>
    <th>Role</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <tr *ngFor="let user of basicTable.data">
    <td>{{user.username}}</td>
    <td>{{user.roleBind|json}}</td>
    <td>
      <nz-button-group>
        <button
          nz-popconfirm
          [nzPopconfirmTitle]="'Are you sure delete this user?'"
          nzPopconfirmPlacement="top"
          [disabled]="isSystem(user)"
          nzType="dashed"
          nz-button
          (nzOnConfirm)="removeUser(user)"
          nzDanger
        >
          <i nz-icon nzType="delete" nzTheme="outline"></i>
        </button>
        <button
          [disabled]="isSystem(user)"
          nz-button
          (click)="unlock(user)"
        >
          <i nz-icon nzType="unlock" nzTheme="outline"></i>
        </button>
        <button
          [disabled]="isSystem(user)"
          nz-button
          (click)="openEditor(user)"
        >
          <i nz-icon nzType="edit" nzTheme="outline"></i>
        </button>
      </nz-button-group>
    </td>
  </tr>
  </tbody>
</nz-table>

// cosky-dashboard/src/pages/User.tsx
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Typography, Table, Button, Space } from 'antd'
import { PlusOutlined, ReloadOutlined } from '@ant-design/icons'

const { Title } = Typography

interface UserData {
  key: string
  username: string
  roles: string[]
  status: string
}

const columns = [
  {
    title: 'Username',
    dataIndex: 'username',
    key: 'username',
  },
  {
    title: 'Roles',
    dataIndex: 'roles',
    key: 'roles',
    render: (roles: string[]) => roles.join(', '),
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
  },
  {
    title: 'Action',
    key: 'action',
    render: () => (
      <Space size="middle">
        <Button type="link">Edit</Button>
        <Button type="link" danger>Delete</Button>
      </Space>
    ),
  },
]

const data: UserData[] = []

export default function User() {
  return (
    <div>
      <div className="content-header">
        <Title level={2}>User Management</Title>
        <Space>
          <Button type="primary" icon={<PlusOutlined />}>
            Add User
          </Button>
          <Button icon={<ReloadOutlined />}>
            Refresh
          </Button>
        </Space>
      </div>
      <div className="content-body">
        <Table columns={columns} dataSource={data} />
      </div>
    </div>
  )
}
