// dashboard/src/pages/config/ConfigEditor.tsx
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, {useEffect, useState} from 'react';
import {Button, Descriptions, Divider, Input, message, Skeleton, Space} from 'antd';
import Editor from '@monaco-editor/react';
import {ConfigFormatSelector} from "./ConfigFormatSelector.tsx";
import {useExecutePromise, useQuery} from "@ahoo-wang/fetcher-react";
import {configApiClient} from "../../services/clients.ts";
import {getFileNameWithExt, getFullFileName} from "./fileNames.ts";
import dayjs from "dayjs";

interface ConfigEditFormProps {
    namespace: string;
    configId?: string;
    onSuccess: () => void;
    onCancel: () => void;
}

export const ConfigEditor: React.FC<ConfigEditFormProps> = ({namespace, configId, onSuccess, onCancel}) => {
    const fileNameWithExt = getFileNameWithExt(configId ?? '.yaml');
    const [fileName, setFileName] = useState<string>(fileNameWithExt.name);
    const [fileExt, setFileExt] = useState<string>(fileNameWithExt.ext);
    const [configData, setConfigData] = useState<string>();
    const {loading, result: config} = useQuery({
        query: configId,
        execute: (query, attributes, abortController) => {
            return configApiClient.getConfig(namespace, query, attributes, abortController);
        }
    })
    const {loading: loadingSave, execute: saveConfig} = useExecutePromise({
        propagateError: true,
        onSuccess: () => {
            message.success('Config saved successfully');
            onSuccess();
        },
        onError: () => {
            message.error('Config save failed');
        }
    })

    useEffect(() => {
        if (config) {
            setConfigData(config.data)
        }
    }, [config, setConfigData]);
    const handleSubmit = () => {
        if (!fileName) {
            message.error('Please enter file name!')
            return;
        }
        const fullFileName = getFullFileName(fileName, fileExt)
        saveConfig(() => {
            return configApiClient.setConfig(namespace, fullFileName, {
                body: configData
            })
        })
    }
    if (configId && loading) {
        return (
            <Skeleton/>
        )
    }
    return (
        <>
            {!configId && (
                <Space.Compact block>
                    <Input disabled={!!configId} placeholder="Enter file name!" value={fileName} onChange={(e) => {
                        setFileName(e.target.value);
                    }}/>
                    <ConfigFormatSelector disabled={!!configId}
                                          value={fileExt}
                                          onChange={(value) => {
                                              setFileExt(value)
                                          }}
                                          defaultValue={'yaml'}
                                          style={{width: 150}}/>
                </Space.Compact>
            )}
            {config && (
                <Descriptions bordered>
                    <Descriptions.Item label="File Name" span={24}>{config.configId}</Descriptions.Item>
                    <Descriptions.Item label="Hash" span={24}>{config.hash}</Descriptions.Item>
                    <Descriptions.Item
                        label="Last Update Time">{dayjs(config.createTime * 1000).format('YYYY-MM-DD HH:mm:ss')}</Descriptions.Item>
                    <Descriptions.Item label="Version">{config.version}</Descriptions.Item>
                </Descriptions>
            )}
            <Divider>Config Data</Divider>
            <Editor
                height="500px"
                theme="vs-dark"
                language={fileExt}
                value={configData}
                onChange={setConfigData}
                options={{
                    minimap: {enabled: false},
                }}
            />
            <Divider></Divider>
            <Space>
                <Button type="primary"
                        onClick={handleSubmit}
                        loading={loadingSave}
                >
                    Submit
                </Button>
                <Button onClick={onCancel}>
                    Cancel
                </Button>
            </Space>
        </>

    );
};

// cosky-dashboard/src/app/components/config/config-editor/config-editor.component.ts
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from '@angular/forms';
import {ConfigDto} from '../../../api/config/ConfigDto';
import {NamespaceContext} from '../../../core/NamespaceContext';
import {NzMessageService} from 'ng-zorro-antd/message';
import {ConfigClient} from '../../../api/config/ConfigClient';
import {ConfigName, Configs} from '../../../api/config/Configs';


@Component({
  selector: 'app-config-editor',
  templateUrl: './config-editor.component.html',
  styleUrls: ['./config-editor.component.scss']
})
export class ConfigEditorComponent implements OnInit {
  validateForm!: FormGroup;
  @Input() configId?: string;
  @Output() afterSet: EventEmitter<boolean> = new EventEmitter<boolean>();
  config!: ConfigDto;
  isAdd = true;
  editorOptions = {theme: 'vs-dark', language: 'yaml'};
  configName!: ConfigName;

  constructor(private namespaceContext: NamespaceContext,
              private configClient: ConfigClient,
              private messageService: NzMessageService,
              private formBuilder: FormBuilder) {

  }

  ngOnInit(): void {
    this.config = Configs.of();
    this.configName = ConfigName.of('.yaml');

    if (this.configId) {
      this.isAdd = false;
      this.configClient.getConfig(this.namespaceContext.ensureCurrentNamespace(), this.configId)
        .subscribe(config => {
          this.config = config;
          this.configName = ConfigName.of(config.configId);
          this.onExtChanged(this.configName.ext);
        });
    }

    const controlsConfig = {
      configName: [this.configName.name, [Validators.required]],
      version: [this.config.version],
      hash: [this.config.hash],
      data: [this.config.data],
      createTime: [this.config.createTime]
    };
    if (!this.isAdd) {
      controlsConfig.configName = [this.configName.name];
    }

    this.validateForm = this.formBuilder.group(controlsConfig);
  }

  setConfig(): void {
    this.config.configId = this.configName.toId();
    this.configClient.setConfig(this.namespaceContext.ensureCurrentNamespace(), this.config.configId, this.config.data)
      .subscribe(result => {
        this.messageService.success(`Config[${this.config.configId}] added successfull!`);
        this.afterSet.emit(result);
      }, error => {
        this.messageService.error(`Config[${this.config.configId}] add failed!\n${error}`);
        this.afterSet.emit(false);
      });
  }

  onExtChanged(configExt: string): void {
    this.configName.ext = configExt;
    const language = Configs.extAsLang(configExt);
    this.editorOptions = Object.assign({}, this.editorOptions, {language});
  }
}

<!--
  ~ Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<form nzLayout="horizontal" nz-form [formGroup]="validateForm" (ngSubmit)="setConfig()">
  <ng-template [ngIf]="isAdd">
    <nz-form-item>
      <nz-form-label [nzSpan]="3" nzRequired>ConfigId</nz-form-label>
      <nz-form-control [nzSpan]="21" nzHasFeedback nzErrorTip="Please enter the ConfigId!">
        <nz-input-group [nzAddOnAfter]="configExt">
          <input type="text" formControlName="configName" nz-input [(ngModel)]="configName.name"/>
        </nz-input-group>
        <ng-template #configExt>
          <nz-select style="width: 120px;" [ngModel]="configName.ext" [ngModelOptions]="{standalone: true}"
                     (ngModelChange)="onExtChanged($event)">
            <nz-option nzLabel=".yaml" nzValue="yaml"></nz-option>
            <nz-option nzLabel=".yml" nzValue="yml"></nz-option>
            <nz-option nzLabel=".json" nzValue="json"></nz-option>
            <nz-option nzLabel=".xml" nzValue="xml"></nz-option>
            <nz-option nzLabel=".text" nzValue="text"></nz-option>
            <nz-option nzLabel=".properties" nzValue="properties"></nz-option>
          </nz-select>
        </ng-template>
      </nz-form-control>
    </nz-form-item>
  </ng-template>
  <ng-template [ngIf]="!isAdd">
    <nz-form-item>
      <nz-form-label [nzSpan]="3">ConfigId</nz-form-label>
      <nz-form-control [nzSpan]="21">
        <input nz-input type="text"
               [ngModel]="config.configId" disabled
               [ngModelOptions]="{standalone: true}"
        />
      </nz-form-control>
    </nz-form-item>
  </ng-template>
  <nz-form-item *ngIf="!isAdd">
    <nz-form-label [nzSpan]="3">Hash</nz-form-label>
    <nz-form-control [nzSpan]="21">
      <input nz-input type="text"
             [ngModel]="config.hash" disabled
             [ngModelOptions]="{standalone: true}"
      />
    </nz-form-control>
  </nz-form-item>
  <nz-form-item *ngIf="!isAdd">
    <nz-form-label [nzSpan]="3">Version</nz-form-label>
    <nz-form-control [nzSpan]="21">
      <input nz-input type="text"
             [ngModel]="config.version" disabled
             [ngModelOptions]="{standalone: true}"
      />
    </nz-form-control>
  </nz-form-item>
  <nz-form-item *ngIf="!isAdd">
    <nz-form-label [nzSpan]="3">CreateTime</nz-form-label>
    <nz-form-control [nzSpan]="21">
      <input nz-input type="text"
             [ngModel]="config.createTime * 1000 | date:'yyyy-MM-dd HH:mm:ss'" disabled
             [ngModelOptions]="{standalone: true}"
      />
    </nz-form-control>
  </nz-form-item>
  <nz-divider nzText="Config Data"></nz-divider>
  <ngx-monaco-editor style="min-height: 600px;"
                     [options]="editorOptions" [(ngModel)]="config.data"
                     [ngModelOptions]="{standalone: true}"
  ></ngx-monaco-editor>

  <nz-divider></nz-divider>
  <nz-form-item>
    <button nz-button nzType="primary" [disabled]="!validateForm.valid" nzSize="large" nzBlock>Submit</button>
  </nz-form-item>
</form>
