// cosky-dashboard/src/pages/Config.tsx
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Typography, Table, Button, Space } from 'antd'
import { PlusOutlined, ReloadOutlined } from '@ant-design/icons'
import { useNamespace } from '../contexts/NamespaceContext'

const { Title } = Typography

interface ConfigData {
  key: string
  configId: string
  version: number
  modifiedTime: string
}

const columns = [
  {
    title: 'Config ID',
    dataIndex: 'configId',
    key: 'configId',
  },
  {
    title: 'Version',
    dataIndex: 'version',
    key: 'version',
  },
  {
    title: 'Modified Time',
    dataIndex: 'modifiedTime',
    key: 'modifiedTime',
  },
  {
    title: 'Action',
    key: 'action',
    render: () => (
      <Space size="middle">
        <Button type="link">View</Button>
        <Button type="link">Edit</Button>
        <Button type="link" danger>Delete</Button>
      </Space>
    ),
  },
]

const data: ConfigData[] = []

export default function Config() {
  const { currentNamespace } = useNamespace()

  return (
    <div>
      <div className="content-header">
        <Title level={2}>Configuration Management</Title>
        <p>Namespace: {currentNamespace}</p>
        <Space>
          <Button type="primary" icon={<PlusOutlined />}>
            Add Config
          </Button>
          <Button icon={<ReloadOutlined />}>
            Refresh
          </Button>
        </Space>
      </div>
      <div className="content-body">
        <Table columns={columns} dataSource={data} />
      </div>
    </div>
  )
}

// cosky-dashboard/src/app/components/config/config.component.ts
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, OnInit} from '@angular/core';
import {ConfigClient} from '../../api/config/ConfigClient';
import {NamespaceContext} from '../../core/NamespaceContext';
import {ConfigEditorService} from './config-editor.service';
import {RowExpand} from '../../model/RowExpand';
import {HttpEventType} from "@angular/common/http";
import {SecurityService} from "../../security/SecurityService";

@Component({
  selector: 'app-config',
  templateUrl: './config.component.html',
  styleUrls: ['./config.component.scss']
})
export class ConfigComponent implements OnInit {
  configs!: string[];
  displayConfigs!: RowExpand<string>[];
  searchVisible = false;
  searchValue = '';

  constructor(private namespaceContext: NamespaceContext,
              private configClient: ConfigClient,
              private configEditorService: ConfigEditorService,
              private securityService: SecurityService) {
  }

  ngOnInit(): void {
    this.getConfigs();
    this.namespaceContext.subscribeNamespaceChanged('/config', namespace => {
      this.getConfigs();
    });
  }


  getConfigs(): void {
    this.configClient.getConfigs(this.namespaceContext.ensureCurrentNamespace()).subscribe(configs => {
      this.configs = configs;
      this.displayConfigs = this.asDisplayData(configs);
    });
  }

  private asDisplayData(configs: string[]): RowExpand<string>[] {
    return this.configs.map(config => RowExpand.of(config));
  }

  removeConfig(configId: string): void {
    this.configClient.removeConfig(this.namespaceContext.ensureCurrentNamespace(), configId).subscribe(result => {
      this.getConfigs();
    });
  }

  openEditConfig(configId?: string): void {
    this.configEditorService.openEditConfig({
      configId, afterSet: (result) => {
        this.getConfigs();
      }
    });
  }

  openImportConfig(): void {
    this.configEditorService.openImportConfig((result) => {
      if (result) {
        this.getConfigs();
      }
    });
  }


  search(): void {
    this.searchVisible = false;
    if (this.searchValue.length === 0) {
      this.displayConfigs = this.asDisplayData(this.configs);
      return;
    }
    this.displayConfigs = this.configs.filter((item) => item.indexOf(this.searchValue) !== -1)
      .map(config => RowExpand.of(config));
  }

  reset(): void {
    this.searchValue = '';
    this.search();
  }

  exportConfigs() {
    this.configClient.exportConfigs(this.namespaceContext.ensureCurrentNamespace()).subscribe();
  }

}

<!--
  ~ Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div nz-row [nzGutter]="8" class="content-header">
  <div nz-col [nzOffset]="15" [nzSpan]="3">
    <button nz-button nzType="primary" nzSize="large" (click)="openEditConfig()" nzBlock>
      <i nz-icon nzType="file-add"></i>Add
    </button>
  </div>
  <div nz-col [nzSpan]="3">
    <button nz-button nzType="primary" nzSize="large" (click)="openImportConfig()" nzDanger nzBlock>
      <i nz-icon nzType="import"></i>Import
    </button>
  </div>
  <div nz-col [nzSpan]="3">
    <a nz-button nzSize="large" (click)="exportConfigs()" nzDanger nzBlock>
      <i nz-icon nzType="export"></i>Export
    </a>
  </div>
</div>

<nz-table class="content-body" #basicTable [nzBordered]="true" [nzData]="displayConfigs" nzShowSizeChanger
          [nzPageSizeOptions]="[10,20,30,50,100]">
  <thead>
  <tr>
    <th>Config Id
      <nz-filter-trigger [(nzVisible)]="searchVisible" [nzActive]="searchValue.length > 0"
                         [nzDropdownMenu]="searchMenu">
        <i nz-icon nzType="search"></i>
      </nz-filter-trigger>
    </th>
    <th>Action</th>
    <th>Expand all versions</th>
  </tr>
  </thead>
  <tbody>
  <ng-template ngFor let-config [ngForOf]="basicTable.data">
    <tr>
      <td>{{config.data}}</td>
      <td>
        <nz-button-group>
          <button
            nz-popconfirm
            [nzPopconfirmTitle]="'Are you sure delete this config?'"
            nzPopconfirmPlacement="top"
            nzType="dashed"
            nz-button
            (nzOnConfirm)="removeConfig(config.data)"
            nzDanger
          >
            <i nz-icon nzType="delete" nzTheme="outline"></i>
          </button>
          <button
            nz-button
            (click)="openEditConfig(config.data)"
          >
            <i nz-icon nzType="edit" nzTheme="outline"></i>
          </button>
        </nz-button-group>
      </td>
      <td [(nzExpand)]="config.expand"></td>
    </tr>
    <ng-template [ngIf]="config.expand">
      <tr [nzExpand]="config.expand">
        <app-config-version-list [configId]="config.data"></app-config-version-list>
      </tr>
    </ng-template>
  </ng-template>
  </tbody>
</nz-table>

<nz-dropdown-menu #searchMenu="nzDropdownMenu">
  <div class="ant-table-filter-dropdown">
    <div class="search-box">
      <input type="text" nz-input [autofocus]="true" placeholder="Search name" [(ngModel)]="searchValue"
             (keyup.enter)="search()"/>
      <button nz-button nzSize="small" nzType="primary" (click)="search()" class="search-button">
        Search
      </button>
      <button nz-button nzSize="small" (click)="reset()">Reset</button>
    </div>
  </div>
</nz-dropdown-menu>
