// dashboard/src/pages/role/RoleEditor.tsx
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useEffect} from 'react';
import {Form, Input, Button, Space, Divider, message} from 'antd';
import {ResourceActionDto, RoleDto, SaveRoleRequest} from "../../generated";
import {useExecutePromise, useQuery} from "@ahoo-wang/fetcher-react";
import {roleApiClient} from "../../services/clients.ts";
import {MinusCircleOutlined, PlusOutlined} from "@ant-design/icons";
import {NamespaceSelector} from "../../components/namespace/NamespaceSelector.tsx";
import {ResourceActionSelector} from "./ResourceActionSelector.tsx";

interface RoleEditorProps {
    initialValues?: RoleDto;
    onSuccess: () => void;
    onCancel: () => void;
}

export interface RoleEditorFormValues extends RoleDto, SaveRoleRequest {

}

export const EMPTY_ARRAY = []

export function RoleEditor({initialValues, onSuccess, onCancel}: RoleEditorProps) {
    const {result = EMPTY_ARRAY} = useQuery<string, ResourceActionDto[]>({
        initialQuery: initialValues?.name,
        execute: (query, attributes, abortController) => {
            return roleApiClient.getResourceBind(query, attributes, abortController);
        }
    })
    const {loading: saveLoading, execute: save} = useExecutePromise({
        onSuccess: () => {
            message.success('Save role success!');
            onSuccess();
            form.resetFields();
        },
        onError: () => {
            message.error('Failed to save role');
        }
    })
    const handleFinish = async (values: RoleEditorFormValues) => {
        await save(() => {
            return roleApiClient.saveRole(values.name, {
                body: values
            })
        })
    };
    const [form] = Form.useForm<RoleEditorFormValues>();

    useEffect(() => {
        if (initialValues) {
            const formValues = {
                name: initialValues.name,
                desc: initialValues.desc ?? "",
                resourceActionBind: result
            }
            form.setFieldsValue(formValues);
        } else {
            form.resetFields();
        }
    }, [initialValues, form, result]);


    return (
        <Form form={form} layout="vertical" onFinish={handleFinish}>
            <Form.Item
                name="name"
                label="Role Name"
                rules={[{required: true, message: 'Please input role name!'}]}
            >
                <Input disabled={!!initialValues}/>
            </Form.Item>
            <Form.Item name="desc" label="Description"
                       rules={[{required: true, message: 'Please input role description!'}]}>
                <Input.TextArea rows={4}/>
            </Form.Item>
            <Divider>Resource Bind</Divider>
            <Form.List name="resourceActionBind">
                {(fields, {add, remove}) => (
                    <>
                        {fields.map(({key, name, ...restField}) => (
                            <Space key={key} style={{display: 'flex', marginBottom: 8}} align="baseline">
                                <Form.Item
                                    {...restField}
                                    name={[name, 'namespace']}
                                    rules={[{required: true, message: 'Missing namespace'}]}
                                >
                                    <NamespaceSelector style={{minWidth: '200px'}}></NamespaceSelector>
                                </Form.Item>
                                <Form.Item
                                    {...restField}
                                    name={[name, 'action']}
                                    rules={[{required: true, message: 'Missing action'}]}
                                >
                                    <ResourceActionSelector style={{minWidth: '200px'}}/>
                                </Form.Item>
                                <MinusCircleOutlined onClick={() => remove(name)}/>
                            </Space>
                        ))}
                        <Form.Item>
                            <Button type="dashed" onClick={() => add()} block icon={<PlusOutlined/>}>
                                Add permissions
                            </Button>
                        </Form.Item>
                    </>
                )}
            </Form.List>
            <Form.Item>
                <Space>
                    <Button type="primary" htmlType="submit" loading={saveLoading}>
                        Submit
                    </Button>
                    <Button onClick={onCancel}>
                        Cancel
                    </Button>
                </Space>
            </Form.Item>
        </Form>
    );
};

// cosky-dashboard/src/app/components/role/role-editor/role-editor.component.ts
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {ResourceActionDto} from "../../../api/role/ResourceActionDto";
import {NamespaceClient} from "../../../api/namespace/NamespaceClient";
import {RoleClient} from "../../../api/role/RoleClient";
import {RoleDto} from "../../../api/role/RoleDto";
import {FormBuilder, FormGroup, Validators} from "@angular/forms";

@Component({
  selector: 'app-role-editor',
  templateUrl: './role-editor.component.html',
  styleUrls: ['./role-editor.component.scss']
})
export class RoleEditorComponent implements OnInit {
  @Input() role!: RoleDto | null;
  @Output() afterSave: EventEmitter<boolean> = new EventEmitter<boolean>();

  resourceActionBind: ResourceActionDto[] = [];
  namespaces: string[] = [];
  roleName!: string;
  desc!: string;
  editorForm!: FormGroup;
  isAdd!: boolean;

  constructor(private namespaceClient: NamespaceClient, private roleClient: RoleClient,
              private formBuilder: FormBuilder) {

  }

  loadRole() {
    if (!this.role) {
      this.isAdd = true;
      return;
    }
    this.isAdd = false;
    this.roleName = this.role.name;
    this.desc = this.role.desc;
    this.roleClient.getResourceBind(this.roleName).subscribe(resp => {
      this.resourceActionBind = resp;
    })
  }

  ngOnInit(): void {
    this.loadRole();
    const controlsConfig = {
      roleName: [this.roleName, [Validators.required]],
      desc: [this.desc, [Validators.required]]
    };
    if (!this.isAdd) {
      controlsConfig.roleName = [this.roleName];
    }
    this.editorForm = this.formBuilder.group(controlsConfig);
    this.namespaceClient.getNamespaces().subscribe(resp => this.namespaces = resp);
  }


  addResourceAction() {
    this.resourceActionBind = [...this.resourceActionBind, {namespace: '', action: 'r'}]
  }

  removeResourceAction(resourceAction: ResourceActionDto) {
    this.resourceActionBind = this.resourceActionBind.filter(resource => resource != resourceAction);
  }

  saveRole() {
    this.roleClient.saveRole(this.roleName, this.desc, this.resourceActionBind).subscribe(resp => {
      this.afterSave.emit(true)
    })
  }
}

<!--
  ~ Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<form nzLayout="horizontal" nz-form [formGroup]="editorForm" (ngSubmit)="saveRole()">
  <ng-template [ngIf]="isAdd">
    <nz-form-item>
      <nz-form-control nzErrorTip="Please input roleName!">
        <nz-input-group nzPrefixIcon="user" nzSize="large">
          <input type="text" nz-input formControlName="roleName" [(ngModel)]="roleName" placeholder="Role Name"/>
        </nz-input-group>
      </nz-form-control>
    </nz-form-item>
  </ng-template>
  <ng-template [ngIf]="!isAdd">
    <nz-form-item>
      <nz-input-group nzPrefixIcon="user" nzSize="large">
        <input type="text" nz-input
               [ngModel]="roleName" disabled
               [ngModelOptions]="{standalone: true}"/>
      </nz-input-group>
    </nz-form-item>
  </ng-template>
  <nz-form-item>
    <nz-form-control nzErrorTip="Please input Role Desc!">
      <nz-input-group nzPrefixIcon="info" nzSize="large">
        <input type="text" nz-input formControlName="desc" [(ngModel)]="desc" placeholder="Role Desc"/>
      </nz-input-group>
    </nz-form-control>
  </nz-form-item>
  <nz-divider nzText="Bind Resource Action"></nz-divider>
  <nz-table #innerTable [nzData]="resourceActionBind" nzSize="middle" [nzShowPagination]="false" [nzBordered]="true">
    <thead>
    <tr>
      <th>Namespace</th>
      <th>Action</th>
      <th>
        <a
          nz-button
          nzType="primary"
          (click)="addResourceAction()"
        >
          <i nz-icon nzType="plus" nzTheme="outline"></i>
        </a></th>
    </tr>
    </thead>
    <tbody>
    <tr *ngFor="let resourceAction of innerTable.data">
      <td>
        <nz-select [(ngModel)]="resourceAction.namespace" [ngModelOptions]="{standalone: true}">
          <nz-option *ngFor="let item of namespaces" [nzLabel]="item" [nzValue]="item"></nz-option>
        </nz-select>
      </td>
      <td>
        <nz-select [(ngModel)]="resourceAction.action" [ngModelOptions]="{standalone: true}">
          <nz-option nzValue="r" nzLabel="Read only"></nz-option>
          <nz-option nzValue="w" nzLabel="Write only"></nz-option>
          <nz-option nzValue="rw" nzLabel="Read and write"></nz-option>
        </nz-select>
      </td>
      <td>
        <a
          nz-button
          nzType="danger"
          (click)="removeResourceAction(resourceAction)"
        >
          <i nz-icon nzType="delete" nzTheme="outline"></i>
        </a>
      </td>
    </tr>
    </tbody>
  </nz-table>
  <nz-divider></nz-divider>
  <button nz-button nzType="primary" [disabled]="!editorForm.valid" nzSize="large" nzBlock>Save Role</button>
</form>
