// cosky-dashboard/src/pages/AuditLog.tsx
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Typography, Table, Button, Space, DatePicker } from 'antd'
import { ReloadOutlined } from '@ant-design/icons'

const { Title } = Typography
const { RangePicker } = DatePicker

interface AuditLogData {
  key: string
  timestamp: string
  action: string
  operator: string
  resource: string
  details: string
}

const columns = [
  {
    title: 'Timestamp',
    dataIndex: 'timestamp',
    key: 'timestamp',
  },
  {
    title: 'Action',
    dataIndex: 'action',
    key: 'action',
  },
  {
    title: 'Operator',
    dataIndex: 'operator',
    key: 'operator',
  },
  {
    title: 'Resource',
    dataIndex: 'resource',
    key: 'resource',
  },
  {
    title: 'Details',
    dataIndex: 'details',
    key: 'details',
  },
]

const data: AuditLogData[] = []

export default function AuditLog() {
  return (
    <div>
      <div className="content-header">
        <Title level={2}>Audit Log</Title>
        <Space>
          <RangePicker />
          <Button icon={<ReloadOutlined />}>
            Refresh
          </Button>
        </Space>
      </div>
      <div className="content-body">
        <Table columns={columns} dataSource={data} />
      </div>
    </div>
  )
}

// cosky-dashboard/src/app/components/audit-log/audit-log.component.ts
/*
 * Copyright [2021-2021] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {Component, OnInit} from '@angular/core';
import {AuditLogClient} from "../../api/audit/AuditLogClient";
import {AuditLogDto} from "../../api/audit/AuditLogDto";
import {NzTableQueryParams} from "ng-zorro-antd/table";

@Component({
  selector: 'app-audit-log',
  templateUrl: './audit-log.component.html',
  styleUrls: ['./audit-log.component.scss']
})
export class AuditLogComponent implements OnInit {
  total: number = 0;
  logs: AuditLogDto[] = [];
  pageIndex: number = 1;
  pageSize: number = 10;
  loading: boolean = true;

  constructor(private auditLogClient: AuditLogClient) {
  }

  ngOnInit(): void {
    this.loadLog();
  }

  loadLog() {
    this.loading = true;
    let offset = (this.pageIndex - 1) * this.pageSize;
    this.auditLogClient.queryLog(offset, this.pageSize).subscribe(resp => {
      this.loading = false;
      this.total = resp.total;
      this.logs = resp.list;
    })
  }

  onQueryParamsChange(params: NzTableQueryParams) {
    const {pageSize, pageIndex, sort, filter} = params;
    this.pageSize = params.pageSize;
    this.pageIndex = params.pageIndex;
    this.loadLog();
  }
}

<!--
  ~ Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<nz-table class="content-body" [nzBordered]="true" [nzData]="logs"
          nzShowSizeChanger
          [nzFrontPagination]="false"
          [nzPageSizeOptions]="[10,20,30,50,100]"
          [nzLoading]="loading"
          [nzTotal]="total"
          [nzPageSize]="pageSize"
          [nzPageIndex]="pageIndex"
          (nzQueryParams)="onQueryParamsChange($event)"
>
  <thead>
  <tr>
    <th>Operator</th>
    <th>ClientIP</th>
    <th>Resource</th>
    <th>Action</th>
    <th>Status</th>
    <th>Msg</th>
    <th>OpTime</th>
  </tr>
  </thead>
  <tbody>
  <tr *ngFor="let log of logs">
    <td>{{log.operator}}</td>
    <td>{{log.ip}}</td>
    <td>{{log.resource}}</td>
    <td>{{log.action}}</td>
    <td>{{log.status}}</td>
    <td>{{log.msg}}</td>
    <td>{{log.opTime | date:'yyyy-MM-dd HH:mm:ss'}}</td>
  </tr>
  </tbody>
</nz-table>
