// cosky-dashboard/src/pages/Role.tsx
/*
 * Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *      http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { Typography, Table, Button, Space } from 'antd'
import { PlusOutlined, ReloadOutlined } from '@ant-design/icons'

const { Title } = Typography

interface RoleData {
  key: string
  roleName: string
  permissions: string[]
  description: string
}

const columns = [
  {
    title: 'Role Name',
    dataIndex: 'roleName',
    key: 'roleName',
  },
  {
    title: 'Permissions',
    dataIndex: 'permissions',
    key: 'permissions',
    render: (permissions: string[]) => permissions.join(', '),
  },
  {
    title: 'Description',
    dataIndex: 'description',
    key: 'description',
  },
  {
    title: 'Action',
    key: 'action',
    render: () => (
      <Space size="middle">
        <Button type="link">Edit</Button>
        <Button type="link" danger>Delete</Button>
      </Space>
    ),
  },
]

const data: RoleData[] = []

export default function Role() {
  return (
    <div>
      <div className="content-header">
        <Title level={2}>Role Management</Title>
        <Space>
          <Button type="primary" icon={<PlusOutlined />}>
            Add Role
          </Button>
          <Button icon={<ReloadOutlined />}>
            Refresh
          </Button>
        </Space>
      </div>
      <div className="content-body">
        <Table columns={columns} dataSource={data} />
      </div>
    </div>
  )
}

// cosky-dashboard/src/app/components/role/role.component.ts
import {Component, OnInit} from '@angular/core';
import {RoleClient} from "../../api/role/RoleClient";
import {NzDrawerService} from "ng-zorro-antd/drawer";
import {RoleEditorComponent} from "./role-editor/role-editor.component";
import {RoleDto} from "../../api/role/RoleDto";

@Component({
  selector: 'app-role',
  templateUrl: './role.component.html',
  styleUrls: ['./role.component.scss']
})
export class RoleComponent implements OnInit {
  roles: RoleDto[] = [];

  constructor(private roleClient: RoleClient, private drawerService: NzDrawerService) {
  }

  loadRoles() {
    this.roleClient.getAllRole().subscribe(resp => {
      this.roles = resp;
    })
  }

  ngOnInit(): void {
    this.loadRoles();
  }

  removeRole(role: RoleDto) {
    this.roleClient.removeRole(role.name).subscribe(resp => {
      this.loadRoles();
    })
  }

  isSystem(role: RoleDto) {
    return 'admin' === role.name;
  }


  openEditor(role: RoleDto | null) {
    const title = role ? `Edit Role [${role.name}]` : 'Add Role';
    const drawerRef = this.drawerService.create<RoleEditorComponent, {}, string>({
      nzTitle: title,
      nzWidth: '40%',
      nzContent: RoleEditorComponent,
      nzContentParams: {
        role
      }
    });
    drawerRef.afterOpen.subscribe(() => {
      drawerRef.getContentComponent()?.afterSave.subscribe(result => {
        if (result) {
          drawerRef.close('Operation successful');
        }
        this.loadRoles();
      });
    });
  }
}

<!--
  ~ Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<div nz-row class="content-header">
  <div nz-col nzOffset="20" [nzSpan]="4">
    <button nz-button nzType="primary" nzSize="large" (click)="openEditor(null)">Add Role
    </button>
  </div>
</div>

<nz-table class="content-body" #basicTable [nzFrontPagination]="false" [nzBordered]="true" [nzData]="roles"
          nzShowSizeChanger
          [nzPageSizeOptions]="[10,20,30,50,100]">
  <thead>
  <tr>
    <th>Role Name</th>
    <th>Desc</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <tr *ngFor="let role of basicTable.data">
    <td>{{role.name}}</td>
    <td>{{role.desc}}</td>
    <td>
      <nz-button-group>
        <button
          nz-popconfirm
          [nzPopconfirmTitle]="'Are you sure delete this role?'"
          nzPopconfirmPlacement="top"
          [disabled]="isSystem(role)"
          nzType="dashed"
          nz-button
          (nzOnConfirm)="removeRole(role)"
          nzDanger
        >
          <i nz-icon nzType="delete" nzTheme="outline"></i>
        </button>
        <button
          [disabled]="isSystem(role)"
          nz-button
          (click)="openEditor(role)"
        >
          <i nz-icon nzType="edit" nzTheme="outline"></i>
        </button>
      </nz-button-group>
    </td>
  </tr>
  </tbody>
</nz-table>
